### ISSUE TITLE
NFS shared folder mount issue in win 8 , virtualbox 5.0.14 , vagrant 1.8

### ISSUE THREAD

**Issue by secretsayan** [WiproOpenSourcePractice/openapphack-vm#7]
There seems to be a "mount" issue in windows 8 , virtualbox 5.0.14 , vagrant 1.8.
 
I am getting the following errors after doing the vagrant up

                                                                                            ==> openapphackvm: Waiting for machine to boot. This may take a few minutes...
    openapphackvm: SSH address: 127.0.0.1:2222
    openapphackvm: SSH username: vagrant
    openapphackvm: SSH auth method: private key
==> openapphackvm: Machine booted and ready!
==> openapphackvm: Checking for guest additions in VM...
==> openapphackvm: [vagrant-hostsupdater] Checking for host entries
==> openapphackvm: [vagrant-hostsupdater] Writing the following entries to (C:/Windows/system32/drivers/etc/hosts)
==> openapphackvm: [vagrant-hostsupdater]   10.20.1.3  openapphackvm.dev  # VAGRANT: a1df56e4bac5b25eab788b41952aa201 (openapphackvm) / 5a8274be-ec73-4c49-8b8f-131d7f5f2a2c
==> openapphackvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> openapphackvm: Setting hostname...
==> openapphackvm: Configuring and enabling network interfaces...
==> openapphackvm: Exporting NFS shared folders...
==> openapphackvm: Preparing to edit nfs mounting file.
[NFS] Status: running
==> openapphackvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

_**mount -o '' 10.20.1.1:'/C/Users/sa272015/Sites/openapphackvm' /var/www/openapphackvm

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount system call failed

**_

**Comment by prathyushr** [comment]
Delete the \HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\provisioners\ansilbe 
Get the same from git https://github.com/mitchellh/vagrant/  and paste over there ,take a reboot ,Run git bash as Administrator ,Install the  the vagrant plugins again .
